config/routes.rb
Geras::Application.routes.draw do

  devise_for :users

  resources :users do as_routes end
  resources :roles do as_routes end
  resources :companies do as_routes end
  resources :users do 
	as_routes
  end
  resources :events do as_routes end
  resources :event_series do as_routes end
    
  get "pages/index"
  get "pages/about"
  get "pages/contact"
 
  get "monitors/application"
  get "monitors/database"
  get "monitors/web"

  match '/monitors',    :to => 'monitors#application'
  match '/database',    :to => 'monitors#database'
  match '/web',    :to => 'monitors#web'

  match '/calendar(/:year(/:month))' => 'calendar#index', :as => :calendar, :constraints => {:year => /\d{4}/, :month => /\d{1,2}/}
  match '/calendar(/:year(/:month(/:day)))' => 'calendar#day', :as => :calendar, :constraints => {:year => /\d{4}/, :month => /\d{1,2}/,:day => /\d{1,2}/}
  match '/calendar/acounting', :to => 'calendar#acounting'
  match '/calendar', :to => 'calendar#index'
  

  root :to => "pages#index"

 match ':controller(/:action(/:id(.:format)))'
end

app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :token_authenticatable, :encryptable, :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable

  # Setup accessible (or protected) attributes for your model
  attr_accessible :email, :password, :password_confirmation, :remember_me
  
  belongs_to :company
  has_and_belongs_to_many :roles
  has_many :events

  def role?(role)
    return !!self.roles.find_by_name(role.to_s.camelize)
  end
  
  def name
    last_name.nil? ? first_name : first_name + " " + last_name
  end
  
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_filter :get_user, :only => [:index,:edit]
  before_filter :accessible_roles, :only => [:new, :edit, :show, :update, :create]
  load_and_authorize_resource :only => [:show,:new,:destroy,:edit,:update]
  
  active_scaffold :user do |config|
	
	config.label = 'Vartotojai' 
	config.columns.exclude :events
    config.columns[:roles].form_ui = :select
	
  end

  def conditions_for_collection
    if current_user.admin?
      "1=1"
    elsif current_user.role? :admin
      "1=1"
    elsif current_user.role? :company
      users = User.find_all_by_company_id current_user.company_id
      ["users.id in (?)", users]
    else
      ["users.id=?", current_user]
    end
  end
  
end

app/helpers/users_helper.rb
module UsersHelper


  
  def options_for_association_conditions(association)
    if association.name == :role
      ['roles.id != ?', Role.find_by_name('Admin').id] unless current_user.admin?
    else
      super
    end
  end
end

app/views/users/shared/_links.erb
<%- if controller_name != 'sessions' %>
  <%= link_to "Prisijunkite", new_session_path(resource_name) %><br />
<% end -%>

<%- if devise_mapping.registerable? && controller_name != 'registrations' %>
  <%= link_to "Prisiregistruokite", new_registration_path(resource_name) %><br />
<% end -%>

<%- if devise_mapping.recoverable? && controller_name != 'passwords' %>
  <%= link_to "Pamiršote slaptažodį?", new_password_path(resource_name) %><br />
<% end -%>

<%- if devise_mapping.confirmable? && controller_name != 'confirmations' %>
  <%= link_to "Negavote prisiregistravimo taisyklių?", new_confirmation_path(resource_name) %><br />
<% end -%>

<%- if devise_mapping.lockable? && resource_class.unlock_strategy_enabled?(:email) && controller_name != 'unlocks' %>
  <%= link_to "Negavote patvirtinimo?", new_unlock_path(resource_name) %><br />
<% end -%>