config/routes.rb
Geras::Application.routes.draw do

  devise_for :users

  resources :users do as_routes end
  resources :roles do as_routes end
  resources :companies do as_routes end
  resources :users do 
	as_routes
  end
  resources :events do as_routes end
  resources :event_series do as_routes end
    
  get "pages/index"
  get "pages/about"
  get "pages/contact"
 
  get "monitors/application"
  get "monitors/database"
  get "monitors/web"

  match '/monitors',    :to => 'monitors#application'
  match '/database',    :to => 'monitors#database'
  match '/web',    :to => 'monitors#web'

  match '/calendar(/:year(/:month))' => 'calendar#index', :as => :calendar, :constraints => {:year => /\d{4}/, :month => /\d{1,2}/}
  match '/calendar(/:year(/:month(/:day)))' => 'calendar#day', :as => :calendar, :constraints => {:year => /\d{4}/, :month => /\d{1,2}/,:day => /\d{1,2}/}
  match '/calendar/acounting', :to => 'calendar#acounting'
  match '/calendar', :to => 'calendar#index'
  

  root :to => "pages#index"

 match ':controller(/:action(/:id(.:format)))'
end

app/models/event.rb
# == Schema Information
# Schema version: 20100330111833
#
# Table name: events
#
#  id              :integer(4)      not null, primary key
#  title           :string(255)
#  starttime       :datetime
#  endtime         :datetime
#  all_day         :boolean(1)
#  created_at      :datetime
#  updated_at      :datetime
#  description     :text
#  event_series_id :integer(4)
#

class Event < ActiveRecord::Base
  attr_accessor :period, :frequency, :commit_button
  
  validates_presence_of :title, :description
  
  belongs_to :event_series
  
  REPEATS = [
              "Does not repeat",
              "Daily"          ,
              "Weekly"         ,
              "Monthly"        ,
              "Yearly"         
  ]
  
  def validate
    if (starttime >= endtime) and !all_day
      errors.add_to_base("Start Time must be less than End Time")
    end
  end
  
  def update_events(events, event)
    events.each do |e|
      begin 
        st, et = e.starttime, e.endtime
        e.attributes = event
        if event_series.period.downcase == 'monthly' or event_series.period.downcase == 'yearly'
          nst = DateTime.parse("#{e.starttime.hour}:#{e.starttime.min}:#{e.starttime.sec}, #{e.starttime.day}-#{st.month}-#{st.year}")  
          net = DateTime.parse("#{e.endtime.hour}:#{e.endtime.min}:#{e.endtime.sec}, #{e.endtime.day}-#{et.month}-#{et.year}")
        else
          nst = DateTime.parse("#{e.starttime.hour}:#{e.starttime.min}:#{e.starttime.sec}, #{st.day}-#{st.month}-#{st.year}")  
          net = DateTime.parse("#{e.endtime.hour}:#{e.endtime.min}:#{e.endtime.sec}, #{et.day}-#{et.month}-#{et.year}")
        end
        #puts "#{nst}           :::::::::          #{net}"
      rescue
        nst = net = nil
      end
      if nst and net
        #          e.attributes = event
        e.starttime, e.endtime = nst, net
        e.save
      end
    end
    
    event_series.attributes = event
    event_series.save
  end
  
  
  
end

app/controllers/events_controller.rb
class EventsController < ApplicationController
  
	active_scaffold :event do |config|
		config.columns.exclude :event_series
	end
  
  
  def index
    
  end
  
  
  def get_events
    @events = Event.find(:all, :conditions => ["starttime >= '#{Time.at(params['start'].to_i).to_formatted_s(:db)}' and endtime <= '#{Time.at(params['end'].to_i).to_formatted_s(:db)}'"] )
    events = [] 
    @events.each do |event|
      events << {:id => event.id, :title => event.title, :description => event.description || "Some cool description here...", :start => "#{event.starttime.iso8601}", :end => "#{event.endtime.iso8601}", :allDay => event.all_day, :recurring => (event.event_series_id)? true: false}
    end
    render :text => events.to_json
  end
  
  
  
  def move
    @event = Event.find_by_id params[:id]
    if @event
      @event.starttime = (params[:minute_delta].to_i).minutes.from_now((params[:day_delta].to_i).days.from_now(@event.starttime))
      @event.endtime = (params[:minute_delta].to_i).minutes.from_now((params[:day_delta].to_i).days.from_now(@event.endtime))
      @event.all_day = params[:all_day]
      @event.save
    end
  end
  
  
  def resize
    @event = Event.find_by_id params[:id]
    if @event
      @event.endtime = (params[:minute_delta].to_i).minutes.from_now((params[:day_delta].to_i).days.from_now(@event.endtime))
      @event.save
    end    
  end
  
  def edit
    @event = Event.find_by_id(params[:id])
  end
  
  def update
    @event = Event.find_by_id(params[:event][:id])
    if params[:event][:commit_button] == "Update All Occurrence"
      @events = @event.event_series.events #.find(:all, :conditions => ["starttime > '#{@event.starttime.to_formatted_s(:db)}' "])
      @event.update_events(@events, params[:event])
    elsif params[:event][:commit_button] == "Update All Following Occurrence"
      @events = @event.event_series.events.find(:all, :conditions => ["starttime > '#{@event.starttime.to_formatted_s(:db)}' "])
      @event.update_events(@events, params[:event])
    else
      @event.attributes = params[:event]
      @event.save
    end

    render :update do |page|
      page<<"$('#calendar').fullCalendar( 'refetchEvents' )"
      page<<"$('#desc_dialog').dialog('destroy')" 
    end
    
  end  
  
  def destroy
    @event = Event.find_by_id(params[:id])
    if params[:delete_all] == 'true'
      @event.event_series.destroy
    elsif params[:delete_all] == 'future'
      @events = @event.event_series.events.find(:all, :conditions => ["starttime > '#{@event.starttime.to_formatted_s(:db)}' "])
      @event.event_series.events.delete(@events)
    else
      @event.destroy
    end
    
    render :update do |page|
      page<<"$('#calendar').fullCalendar( 'refetchEvents' )"
      page<<"$('#desc_dialog').dialog('destroy')" 
    end
    
  end
  
    def acounting
    @format = ("iso_date").to_sym


    start_d, end_d = params[:start_d] || Time.now, params[:end_d] || Time.now

    if current_user.admin?
      @users = User.find(:all)
      @companies = Company.find(:all)
    elsif current_user.role? :admin
      @users = User.find_all_by_company_id current_user.company.id
      @companies = Company.find(:first, :conditions => {:company_id => current_user.company.id})
    elsif current_user.role? :company
      @users = User.find_all_by_company_id current_user.company.id
      @companies = Company.find(:first, :conditions => {:company_id => current_user.company.id})
    else
      @users = [current_user]
      @companies = current_user.company_id? ? [  current_user.company_id ] : []
    end

    cond = [" 1=1"]

    if params[:Vartotojai]
      
      cond[0] << " AND user_id in (?)"
      cond << params[:Vartotojai]
    end
    if params[:Kompanijos]
      cond[0] << " AND user_id in (?)"
      cond << User.find(:all, :conditions => {:company_id => params[:Kompanijos]})
    end
    if params[:start_d]
      if params[:end_d]
        cond[0] << " and ( DATE(events.end_at) >= ? and DATE(events.start_at) <= ? )"
        cond << params[:start_d] << params[:end_d]
      else
        cond[0] << " and (? between DATE(events.start_at) and DATE(events.end_at)) or (? between DATE(events.start_at) and DATE(events.end_at))"
        cond << params[:start_d] << params[:start_d]
      end

    end


    
    @events = Event.find(:all, :conditions => cond)

  end
  
end

app/helpers/events_helper.rb
module EventsHelper

end

app/views/events/_acount_list.html.erb
<acounting>
  <%= 'Ataskaita'  %>
  <table>

      <% @events.each do |event| %>

        <tr>
          <td><%= event.start_at %> &nbsp; <%=  event.end_at %></td>
          <td><%= event.name %></td>
          <td><%= event.description %></td>

        </tr>

        
    <% end %>
  </table>
</acounting>

app/views/events/_acounting.html.erb
<acounting>
  <table>

      <% @events.each do |event| %>

        <tr>
          <td><%= event.start_at %> &nbsp; <%=  event.end_at %></td>
          <td><%= event.name %></td>
          <td><%= event.description %></td>

        </tr>

        
    <% end %>
  </table>
</acounting>

app/views/events/_edit_form.html.erb
<%remote_form_for @event, :url => {:action => :update} , :before => "$('#updating_events').show();", :complete => "$('#updating_events').hide();" do |f| %>
<p>
  <%=f.label :title %>
  <br/>
  <%=f.text_field :title %>
</p>
<p>
  <%=f.label :description %>
  <br/>
  <%=f.text_area :description, :rows => 4, :cols => 30 %>
</p>
<p>
  <%=f.label :starttime, 'Start Time' %>
  <br/>
  <%=f.datetime_select :starttime %>
</p>
<p>
  <%=f.label :endtime, 'End Time' %>
  <br/>
  <%=f.datetime_select :endtime %>
</p>
<p>
  <%=f.label :all_day %>
  <%=f.check_box :all_day %>
</p>
<%if false%>
<%period = (@event.event_series)?@event.event_series.period : nil -%>
<p>
  <%=f.label :period, "Repeats" %>
  <%=f.select :period, Event::REPEATS,{:selected => period}, :onchange => "showPeriodAndFrequency(this.value);" %>
</p>
<%frequency = (@event.event_series)?@event.event_series.frequency : nil -%>
<p id = "frequency" style = "display:<%(period)? '' : 'none'%>;">
  <%=f.label :frequency, "Repeat every" %>
  <%=f.select :frequency, (1..30).to_a, {:selected => frequency} %> <span id = "period"></span>
</p>
<%end%>
<%=f.hidden_field :id, :value => @event.id%>
<%=f.hidden_field :commit_button, :value => ""%>
<p>
  <%if @event.event_series -%>
  <%=f.submit 'Update Only This Occurrence', :onclick => "document.getElementById('event_commit_button').value = this.value"%>
  <%=f.submit 'Update All Occurrence', :onclick => "document.getElementById('event_commit_button').value = this.value"%>
  <%=f.submit 'Update All Following Occurrence', :onclick => "document.getElementById('event_commit_button').value = this.value"%>
  <%else-%>
  <%=f.submit 'Update', :onclick => "document.getElementById('event_commit_button').value = this.value"%>
  <%end-%>
  
  <span id = "updating_events" style = "display:none;">Updating, Please wait...</span>
</p>
<%end %>

app/views/events/_events.html.erb
<events>
  <table>
    <% @events.each do |event| %>
      <tr>
        <td><%= event.start_at %> &nbsp; <%=  event.end_at %></td>
        <td><%= event.name %></td>
        <td><%= event.description %></td>
      </tr>
    <% end %>
  </table>
</events>

app/views/events/_filter.html.erb
<h1>Kalendorius</h1>
<div style="float:left;"> 
  <%= link_to_if(can?(:manage, Event), 'Sukurti įvykius', new_event_path) %>
</div>


<div style="float:right;"><%= 'Pasirinkite datą' %>
 

<input type="text" id="filterdate" class="hasDatepicker">
  <%= button_to_function 'Žiūrėti',  "location.href='#{url_for(:action => 'index')}/'+$('year_value').value+'/'+$('month_value').value+'/'+$('day_value').value"  %>
</div>
<br />

<div>
   <%= button_to "Ataskaitos", url_for(:action => 'acounting') %>
</div>

<script>
$('#filterdate').datepicker();
</script>

app/views/events/_form.html.erb
<%form_for @event, :remote=>true do |f| %>
<p>
  <%=f.label :title %>
  <br/>
  <%=f.text_field :title %>
</p>
<p>
  <%=f.label :description %>
  <br/>
  <%=f.text_area :description, :rows => 4, :cols => 30 %>
</p>
<p>
  <%=f.label :starttime, 'Start Time' %>
  <br/>
  <%=f.datetime_select :starttime %>
</p>
<p>
  <%=f.label :endtime, 'End Time' %>
  <br/>
  <%=f.datetime_select :endtime %>
</p>
<p>
  <%=f.label :all_day %>
  <%=f.check_box :all_day %>
</p>
<p>
  <%=f.label :period, "Repeats" %>
  <%=f.select :period, Event::REPEATS,{}, :onchange => "showPeriodAndFrequency(this.value);" %>
</p>
<p id = "frequency" style = "display:none;">
  <%=f.label :frequency, "Repeat every" %>
  <%=f.select :frequency, (1..30).to_a %> <span id = "period"></span>
</p>
<%=f.hidden_field :id, :value => @event.id %>
<p>
  <%=f.submit 'Create' %> <span id = "creating_events" style = "display:none;">Creating, Please wait...</span>
</p>
<%end %>

app/views/events/acounting.html.erb
<h5>Ataskaitos</h5>

<%= form_tag :action => :acounting do %>
  <table>
    <tr>
      <td style="width:33%">
        Vartotojai
      </td>
      <td>
        Kompanijos
      </td>
      <td>
        Data
      </td>

    </tr>
    <tr>
      <td>
        <%=  select_tag "Vartotojai", options_from_collection_for_select(@users, "id", "name"), {:multiple=>true, :style=>"width:200px"}  %>
      </td>
      <td>
        <%=  select_tag "Kompanijos", options_from_collection_for_select(@companies, "id", "name"), {:multiple=>true, :style=>"width:200px"}  %>
      </td>
      <td>
        
        <%= 'Nuo' %>
		<input type="text" value="" id="filterdateNuo" name="filterdateNuo" class="hasDatepicker">
        <br />
        <%= 'Iki' %>
		<input type="text" value="" id="filterdateIki" name="filterdateIki" class="hasDatepicker">
      </td>
    </tr>

  </table>

  <div style="width: 100%; vertical-align: middle; text-align: center;"><%= submit_tag 'Generuoti' %></div>

<% end %>

<%= render :partial => 'acount_list' %>
<script>
$('#filterdateNuo').datetimepicker();
$('#filterdateIki').datetimepicker();
</script>

app/views/events/day.html.erb
<span id='year_value' />
<span id='month_value' />
<span id='day_value' />

<%= render :partial => 'filter' %>

<%= raw(event_calendar) %>
<br />
<%= render :partial => 'events' %>

app/views/events/index.html.erb
<%= javascript_include_tag 'calendar.js' %>
<%= javascript_include_tag 'fullcalendar.js' %>
<%= javascript_include_tag 'gcal.js' %>

<script>
  $(document).ready(function(){
      // page is now ready, initialize the calendar...
      $('#calendar').fullCalendar({
          editable: true,
          header: {
              left: 'prev,next today',
              center: 'title',
              right: 'month,agendaWeek,agendaDay'
          },
          defaultView: 'agendaWeek',
          height: 500,
          slotMinutes: 15,
          loading: function(bool){
              if (bool) 
                  $('#loading').show();
              else 
                  $('#loading').hide();
          },
          events: "/events/get_events",
          timeFormat: 'h:mm t{ - h:mm t} ',
          dragOpacity: "0.5",
          eventDrop: function(event, dayDelta, minuteDelta, allDay, revertFunc){
//              if (confirm("Are you sure about this change?")) {
                  moveEvent(event, dayDelta, minuteDelta, allDay);
//              }
//              else {
//                  revertFunc();
//              }
          },
          
          eventResize: function(event, dayDelta, minuteDelta, revertFunc){
//              if (confirm("Are you sure about this change?")) {
                  resizeEvent(event, dayDelta, minuteDelta);
//              }
//              else {
//                  revertFunc();
//              }
          },
          
          eventClick: function(event, jsEvent, view){
              showEventDetails(event);
          },
      
      
      
      
      });
  });
</script>

<%= render :partial => 'filter' %>

<br>
<div>
  <div id='calendar'>
  </div>
</div>
<div id = "desc_dialog" style ="display:none;">
  <div id = "event_desc">
  </div>
  <br/>
  <br/>
  <div id = "event_actions">
    <span id = "edit_event"></span>
    <span id = "delete_event"></span>
  </div>
</div>
<div id = "create_event_dialog" style ="display:none;">
  <div id = "create_event">
  </div>
</div>