config/routes.rb
Geras::Application.routes.draw do

  devise_for :users

  resources :users do as_routes end
  resources :roles do as_routes end
  resources :companies do as_routes end
  resources :users do 
	as_routes
  end
  resources :events do as_routes end
  resources :event_series do as_routes end
    
  get "pages/index"
  get "pages/about"
  get "pages/contact"
 
  get "monitors/application"
  get "monitors/database"
  get "monitors/web"

  match '/monitors',    :to => 'monitors#application'
  match '/database',    :to => 'monitors#database'
  match '/web',    :to => 'monitors#web'

  match '/calendar(/:year(/:month))' => 'calendar#index', :as => :calendar, :constraints => {:year => /\d{4}/, :month => /\d{1,2}/}
  match '/calendar(/:year(/:month(/:day)))' => 'calendar#day', :as => :calendar, :constraints => {:year => /\d{4}/, :month => /\d{1,2}/,:day => /\d{1,2}/}
  match '/calendar/acounting', :to => 'calendar#acounting'
  match '/calendar', :to => 'calendar#index'
  

  root :to => "pages#index"

 match ':controller(/:action(/:id(.:format)))'
end

app/controllers/monitors_controller.rb
class MonitorsController < ApplicationController
  before_filter :authenticate_user!
  def application
  end

  def database
  end

  def web
  end

end

app/helpers/monitors_helper.rb
module MonitorsHelper
end

app/views/monitors/_menu.html.erb
  <nav class="round" style="float:left;">
    <ul>
        <li>
          <%= link_to('Aplikacija', monitors_path) %>
        </li>
        <li>
          <%= link_to('Duomenų bazė', database_path) %>
        </li>
        <li>
          <%= link_to('Prognozė', web_path)  %>
        </li>
    </ul>
  </nav>

app/views/monitors/application.html.erb
<%= render :partial => 'menu' %>



<iframe src="https://heroku.newrelic.com/public/charts/4ZfP05awFy4" width="500" height="300" scrolling="no" frameborder="no"></iframe>
<iframe src="https://heroku.newrelic.com/public/charts/egkJS2OpsZy" width="500" height="300" scrolling="no" frameborder="no"></iframe>
<iframe src="https://heroku.newrelic.com/public/charts/aHgFhQpIiXu" width="500" height="300" scrolling="no" frameborder="no"></iframe>

app/views/monitors/database.html.erb
<%= render :partial => 'menu' %>
<iframe src="https://heroku.newrelic.com/public/charts/i7puLg2rQuI" width="500" height="300" scrolling="no" frameborder="no"></iframe>
<iframe src="https://heroku.newrelic.com/public/charts/cfn6sOR2EAy" width="500" height="300" scrolling="no" frameborder="no"></iframe>
<iframe src="https://heroku.newrelic.com/public/charts/hlhWKklA9Ev" width="500" height="300" scrolling="no" frameborder="no"></iframe>

app/views/monitors/web.html.erb
<%= render :partial => 'menu' %>


<iframe src="https://heroku.newrelic.com/public/charts/hOEqfapmvth" width="500" height="300" scrolling="no" frameborder="no"></iframe>
<iframe src="https://heroku.newrelic.com/public/charts/5lLASsDFC0J" width="500" height="300" scrolling="no" frameborder="no"></iframe>
<iframe src="https://heroku.newrelic.com/public/charts/NVwZvQ3CSH" width="500" height="300" scrolling="no" frameborder="no"></iframe>