config/routes.rb
Geras::Application.routes.draw do

  devise_for :users

  resources :users do as_routes end
  resources :roles do as_routes end
  resources :companies do as_routes end
  resources :users do 
	as_routes
  end
  resources :events do as_routes end
  resources :event_series do as_routes end
    
  get "pages/index"
  get "pages/about"
  get "pages/contact"
 
  get "monitors/application"
  get "monitors/database"
  get "monitors/web"

  match '/monitors',    :to => 'monitors#application'
  match '/database',    :to => 'monitors#database'
  match '/web',    :to => 'monitors#web'

  match '/calendar(/:year(/:month))' => 'calendar#index', :as => :calendar, :constraints => {:year => /\d{4}/, :month => /\d{1,2}/}
  match '/calendar(/:year(/:month(/:day)))' => 'calendar#day', :as => :calendar, :constraints => {:year => /\d{4}/, :month => /\d{1,2}/,:day => /\d{1,2}/}
  match '/calendar/acounting', :to => 'calendar#acounting'
  match '/calendar', :to => 'calendar#index'
  

  root :to => "pages#index"

 match ':controller(/:action(/:id(.:format)))'
end

app/helpers/layout_helper.rb
# These helper methods can be called in your template to set variables to be used in the layout
# This module should be included in all views globally,
# to do so you may need to add this line to your ApplicationController
#   helper :layout
module LayoutHelper
  def title(page_title, show_title = true)
    @content_for_title = page_title.to_s
    @show_title = show_title
  end
  
  def show_title?
    @show_title
  end
  
  def stylesheet(*args)
    content_for(:head) { stylesheet_link_tag(*args) }
  end
  
  def javascript(*args)
    content_for(:head) { javascript_include_tag(*args) }
  end
end

app/views/layouts/_footer.html.erb
<footer>
  <nav class="round">
    <ul>
      <li>Copyright © 2011 v1.0b </li>
    </ul>
  </nav>
</footer>

app/views/layouts/_header.html.erb
<header>
  <nav class="round" style="float:left;">
    <ul>
      
        <% if user_signed_in? %>
        <li>
          <%= link_to_if(can?(:read, User), 'Vartotojai', users_path) %>
        </li>
        <li>
          <%= link_to_if(can?(:read, Company), 'Kompanijos', companies_path) %>
        </li>
        <li>
          <%= link_to_if(can?(:read, Event),'Planai', events_path)  %>
        </li>
        <li>
          <%= link_to_if(can?(:read, Role),'Roles', roles_path)  %>
        </li>
		<li>
          <%= link_to_if(current_user.admin?,'Statistika', monitors_path)  %>
        </li>
      <% else %>
				<li>
					<%= link_to('Pradinis', root_path) %>
				</li>

      <% end %>
      
    </ul>
  </nav>
  <nav class="round" style="float:right;">
    <ul>
      <li>
        <% if user_signed_in? %>
        <li>
          <%= link_to('Redaguoti prisijungimą', edit_user_registration_path) %>
        </li>
        <li>
          <%= link_to('Atsijungti', destroy_user_session_path) %>
        </li>
      <% else %>
        <li>
          <%= link_to('Prisijungti', new_user_session_path)  %>
        </li>
      <% end %>
      </li>
    </ul>
  </nav>
</header>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
	<head>
		<title><%= yield(:title) || "LAPS" %></title>
		<%= stylesheet_link_tag 'fullcalendar'%>
		<%= stylesheet_link_tag 'blueprint/screen', :media => 'screen' %>
		<%= stylesheet_link_tag 'blueprint/print',  :media => 'print' %>
		<!--[if lt IE 8]><%= stylesheet_link_tag 'blueprint/ie' %><![endif]-->
		<%= stylesheet_link_tag 'custom', :media => 'screen' %>
	<%= stylesheet_link_tag 'http://ajax.googleapis.com/ajax/libs/jqueryui/1.8.9/themes/ui-lightness/jquery-ui.css' %>
  <%# javascript_include_tag :defaults %>
  <%= javascript_include_tag 'http://ajax.googleapis.com/ajax/libs/jquery/1.4.4/jquery.js' %>
  <%= javascript_include_tag 'rails_jquery.js' %>
  <%= javascript_include_tag 'http://ajax.googleapis.com/ajax/libs/jqueryui/1.8.9/jquery-ui.js' %>
  <%= javascript_include_tag 'jquery-ui-timepicker-addon.js' %>
  <%= javascript_include_tag 'application.js' %>
		
		<%= active_scaffold_includes %>
		<%= csrf_meta_tag %>
	</head>
	<body>
		<div class="container">
		    <%= image_tag("laps1.jpg", :alt => "LASP", :class => "round") %>
			<%= render 'layouts/header' %>
			<section class="round">
				<% flash.each do |key, message| %>
				<%= content_tag(:div, message, :class => "flash #{key}") %>
				<% end %>
				<%= yield %>
			</section>
			<%= render 'layouts/footer' %>
		</div>
	</body>
</html>